### ISSUE TITLE
Presentation scroll view detection conflicts with UITableView editing gesture

### ISSUE THREAD

**Issue by PhilipDukhov** [nathantannar4/Transmission#19]
We don't like how `onDrag` behavior works, so switching to `UITableView` which looks much cleaner.

But table view reorder gesture gets interrupted by `presentation` scrolling detection

<img src="https://github.com/nathantannar4/Transmission/assets/6103621/9ba9503a-b0da-4191-9072-1201816addec" width="300" />

Sample:
```swift
struct ContentView: View {
    @State var visible = false

    var body: some View {
        Toggle("show sheet", isOn: $visible)
            .presentation(
                transition: .slide(
                    options: .init(
                        edge: .bottom,
                        prefersScaleEffect: true,
                        isInteractive: true,
                        options: .init(
                            shouldAutomaticallyDismissDestination: false,
                            modalPresentationCapturesStatusBarAppearance: true,
                            preferredPresentationBackgroundColor: .white
                        )
                    )
                ),
                isPresented: $visible
            ) {
                VStack {
                    UIList(editing: true)
                }
            }
    }

    struct UIList: UIViewRepresentable {
        let editing: Bool

        func makeUIView(context: Context) -> Table {
            Table()
        }

        func updateUIView(_ uiView: Table, context: Context) {
            uiView.set(editing: editing)
        }

        class Table: UITableView, UITableViewDelegate, UITableViewDataSource {
            init() {
                super.init(frame: .zero, style: .grouped)
                register(UITableViewCell.self, forCellReuseIdentifier: "id")
                delegate = self
                dataSource = self
                translatesAutoresizingMaskIntoConstraints = false
            }

            func set(editing: Bool) {
                setEditing(editing, animated: true)
            }

            required init?(coder: NSCoder) {
                fatalError("init(coder:) has not been implemented")
            }

            func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
                10
            }

            func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: "id", for: indexPath)
                cell.textLabel?.text = String(describing: indexPath)
                return cell
            }

            func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCell.EditingStyle {
                .none
            }

            func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
                true
            }

            func tableView(_ tableView: UITableView, moveRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath) {

            }
        }
    }
}
```

**Comment by nathantannar4** [comment]
Fixed in 1.0.3

**Comment by PhilipDukhov** [comment]
Hey @nathantannar4! The bug came back since 1.4.2, was working fine in 1.4.1. 

You can reproduce it with the sample code from this question, could we reopen it?

**Comment by nathantannar4** [comment]
Sorry about that! Fixed again in `1.4.6`. Yea I'd love to have CI and tests I just havent had the time to get that setup

**Comment by PhilipDukhov** [comment]
> Sorry about that! Fixed again in 1.4.6. Yea I'd love to have CI and tests I just havent had the time to get that setup

thank you for a fast fix!

Unfortunately it's not full, my initial sample didn't contained an outer scroll view - we need it to update navigation bar background, so we render whole `UITable` no matter how many items are there we don't expect too many.

Updated example, working fine in 1.4.1 but not in 1.4.6

```swift
struct ContentView: View {
    @State var visible = false

    var body: some View {
        Toggle("show sheet", isOn: $visible)
            .presentation(
                transition: .slide(
                    options: .init(
                        edge: .bottom,
                        prefersScaleEffect: true,
                        isInteractive: true,
                        options: .init(
                            shouldAutomaticallyDismissDestination: false,
                            modalPresentationCapturesStatusBarAppearance: true,
                            preferredPresentationBackgroundColor: .white
                        )
                    )
                ),
                isPresented: $visible
            ) {
                ScrollView {
                    UIList(editing: true)
                        .frame(height: 1000)
                }
            }
    }

    struct UIList: UIViewRepresentable {
        let editing: Bool

        func makeUIView(context: Context) -> Table {
            Table()
        }

        func updateUIView(_ uiView: Table, context: Context) {
            uiView.set(editing: editing)
        }

        class Table: UITableView, UITableViewDelegate, UITableViewDataSource {
            init() {
                super.init(frame: .zero, style: .grouped)
                register(UITableViewCell.self, forCellReuseIdentifier: "id")
                delegate = self
                dataSource = self
                translatesAutoresizingMaskIntoConstraints = false
            }

            func set(editing: Bool) {
                setEditing(editing, animated: true)
            }

            required init?(coder: NSCoder) {
                fatalError("init(coder:) has not been implemented")
            }

            func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
                10
            }

            func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: "id", for: indexPath)
                cell.textLabel?.text = String(describing: indexPath)
                return cell
            }

            func tableView(_ tableView: UITableView, editingStyleForRowAt indexPath: IndexPath) -> UITableViewCell.EditingStyle {
                .none
            }

            func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
                true
            }

            func tableView(_ tableView: UITableView, moveRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath) {

            }
        }
    }
}
```

**Comment by nathantannar4** [comment]
1.4.8 👍🏻
